=== navikt/Sykmelding_v1.4/konfigurasjon v1.4/xsd/SM2013DynaSpm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 sp1 (x64) (http://www.altova.com) by XMLSpy 2009 Enterprise Ed., Installed for 30 users (with SMP from 2009-06-19 to 2010-06-20) (NAV ØKONOMITJENESTER) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://nav.no/dokument/ekstern/sykmelding/dynamiskregelsett/SM2013DynaSpm/v1" targetNamespace="http://nav.no/dokument/ekstern/sykmelding/dynamiskregelsett/SM2013DynaSpm/v1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="SM2013DynaSpm">
		<xs:annotation>
			<xs:documentation>Ineholder definisjon av dynamiske spørsmål</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RegelSettVersjon" type="xs:string">
					<xs:annotation>
						<xs:documentation>Versjon av regelsett</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="DynaGruppe" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Grupperer spørsmål i grupper</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="DynaGruppeId" type="xs:string">
								<xs:annotation>
									<xs:documentation>Gruppens id på formen 6.1</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="DynaGruppeTekst" type="xs:string">
								<xs:annotation>
									<xs:documentation>Gruppetekst benyttes til oversrift på spørsmål som tilhører gruppen</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Beskrivelse" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Beskrivelse av gruppen, benyttes som hjelpetekst på overskriftsnivå</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="DynaRegler" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>En kommaseparert liste med regelnavn som definert i SM2013DynaRegel. Hvis en ragel evaluerere til false blir ihele gruppen skjult og ingen spørsmål vises</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Obligatorisk" type="xs:string" minOccurs="0"/>
							<xs:element name="DynaSpm" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>En spørsmålsgruppe består av en eller flere spørsmål</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DynaSpmId" type="xs:string">
											<xs:annotation>
												<xs:documentation>Gruppens id på formen 6.1.1</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="DynaSpmTekst" type="xs:string">
											<xs:annotation>
												<xs:documentation>Spørsmålets ledetekst</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="Beskrivelse" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Beskrivelse av spørsmålet.  Benyttes som hjelpetekst</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="DynaRegler" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>En kommaseparert liste med regelnavn som definert i SM2013DynaRegel. Benyttes til å skjule enkeltspørsmål</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="Restriksjon" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Angir om spørsmålet skal vises i utsriftsdelen.  Foreløpig er det kun verdien "Arbeidsgiver" som benyttes  for del C</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="Obligatorisk" type="xs:string" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="navn" type="xs:string" use="optional">
										<xs:annotation>
											<xs:documentation>Valgfritt navn på spørsmålet</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="navn" type="xs:string" use="optional">
							<xs:annotation>
								<xs:documentation>Valgfrittnavn på gruppen</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== navikt/Sykmelding_v1.4/konfigurasjon v1.4/SM2013DynaSpm_v1_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<SM2013DynaSpm xsi:schemaLocation="http://nav.no/dokument/ekstern/sykmelding/dynamiskregelsett/SM2013DynaSpm/v1 SM2013DynaSpm.xsd" xmlns="http://nav.no/dokument/ekstern/sykmelding/dynamiskregelsett/SM2013DynaSpm/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<RegelSettVersjon>3</RegelSettVersjon>
		<!--  7 uker  -->
		<DynaGruppe>  
		<DynaGruppeId>6.3</DynaGruppeId>
		<DynaGruppeTekst>Opplysninger ved vurdering av aktivitetskravet og NAVs oppfølging</DynaGruppeTekst>
		<Beskrivelse>Utdypende opplysninger ved uke 7 (til NAVs vurdering av aktivitetskravet)</Beskrivelse>
		<DynaRegler>UtdypendeOpplysninger1</DynaRegler>
		<DynaSpm>
			<DynaSpmId>6.3.1</DynaSpmId>
			<DynaSpmTekst>Beskriv kort sykehistorie, symptomer og funn. Hvordan påvirker helsetilstanden funksjonen i arbeid og dagligliv?</DynaSpmTekst>
			<Beskrivelse></Beskrivelse>
			<Restriksjon>A</Restriksjon>
		</DynaSpm>
		<DynaSpm>
			<DynaSpmId>6.3.2</DynaSpmId>
			<DynaSpmTekst>Beskriv pågående og planlagt utredning og/eller behandling. Lar dette seg kombinere med delvis arbeid?</DynaSpmTekst>
			<Beskrivelse></Beskrivelse>
			<Restriksjon>A</Restriksjon>
		</DynaSpm>
	</DynaGruppe>
	<DynaGruppe>  <!-- 17 uker -->
		<DynaGruppeId>6.4</DynaGruppeId>
		<DynaGruppeTekst>Helseopplysninger til NAVs videre vurdering av oppfølging</DynaGruppeTekst>
		<Beskrivelse>Utdypende opplysninger ved uke 17 (til NAVs vurdering av oppfølgingen)</Beskrivelse>
		<DynaRegler>UtdypendeOpplysninger2</DynaRegler>
		<DynaSpm>
			<DynaSpmId>6.4.1</DynaSpmId>
			<DynaSpmTekst>Beskriv kort sykdomsutviklingen, symptomer og funn. Hvordan påvirker helsetilstanden funksjonen i arbeid og dagligliv?</DynaSpmTekst>
			<Beskrivelse></Beskrivelse>
			<Restriksjon>A</Restriksjon>
		</DynaSpm>
		<DynaSpm>
			<DynaSpmId>6.4.2</DynaSpmId>
			<DynaSpmTekst>Beskriv pågående og planlagt utredning og/eller behandling. Lar dette seg kombinere med delvis arbeid?</DynaSpmTekst>
			<Beskrivelse></Beskrivelse>
			<Restriksjon>A</Restriksjon>
		</DynaSpm>
		<DynaSpm>
			<DynaSpmId>6.4.3</DynaSpmId>
			<DynaSpmTekst>Hva mener du skal til for at pasienten kan komme tilbake i eget eller annet arbeid?</DynaSpmTekst>
			<Beskrivelse></Beskrivelse>
			<Restriksjon>A</Restriksjon>
		</DynaSpm>
	</DynaGruppe>
	<DynaGruppe>  <!-- 39 uker -->
		<DynaGruppeId>6.5</DynaGruppeId>
		<DynaGruppeTekst>Helseopplysninger til NAVs videre vurdering av oppfølging</DynaGruppeTekst>
		<Beskrivelse>Utdypende opplysninger ved uke 39 uker (mot slutten av sykepengeperioden)</Beskrivelse>
		<DynaRegler>UtdypendeOpplysninger3</DynaRegler>
		<DynaSpm>
			<DynaSpmId>6.5.1</DynaSpmId>
			<DynaSpmTekst>Beskriv kort sykdomsutviklingen, symptomer og funn. Hvordan påvirker helsetilstanden funksjonen i arbeid og dagligliv?</DynaSpmTekst>
			<Beskrivelse></Beskrivelse>
			<Restriksjon>A</Restriksjon>
		</DynaSpm>
		<DynaSpm>
			<DynaSpmId>6.5.2</DynaSpmId>
			<DynaSpmTekst>Beskriv pågående og planlagt utredning og/eller behandling. Lar dette seg kombinere med delvis arbeid?</DynaSpmTekst>
			<Beskrivelse></Beskrivelse>
			<Restriksjon>A</Restriksjon>
		</DynaSpm>
		<DynaSpm>
			<DynaSpmId>6.5.3</DynaSpmId>
			<DynaSpmTekst>Kan arbeidsevnen bedres gjennom medisinsk behandling og/eller arbeidsrelatert aktivitet? I så fall hvordan? Angi tidsperspektiv</DynaSpmTekst>
			<Beskrivelse></Beskrivelse>
			<Restriksjon>A</Restriksjon>
		</DynaSpm>
	</DynaGruppe>
	<!-- dynagruppe AAP -->
	<DynaGruppe>  
		<DynaGruppeId>6.6</DynaGruppeId>
		<DynaGruppeTekst>Helseopplysninger dersom pasienten søker om AAP</DynaGruppeTekst>
		<Beskrivelse>Husk at pasienten selv må søke om AAP</Beskrivelse>
		<DynaRegler>UtdypendeOpplysninger3</DynaRegler>
		<Obligatorisk>N</Obligatorisk> 
		<DynaSpm>
			<DynaSpmId>6.6.1</DynaSpmId>
			<DynaSpmTekst>Hva antar du at pasienten kan utføre av eget arbeid/arbeidsoppgaver i dag eller i nær framtid?</DynaSpmTekst>
			<Beskrivelse></Beskrivelse>
			<Restriksjon>A</Restriksjon>
			<Obligatorisk>N</Obligatorisk> 
		</DynaSpm>
		<DynaSpm>
			<DynaSpmId>6.6.2</DynaSpmId>
			<DynaSpmTekst>Hvis pasienten ikke kan gå tilbake til eget arbeid, hva antar du at pasienten kan utføre av annet arbeid/arbeidsoppgaver?</DynaSpmTekst>
			<Beskrivelse></Beskrivelse>
			<Restriksjon>A</Restriksjon>
			<Obligatorisk>N</Obligatorisk>
		</DynaSpm>
		<DynaSpm>
			<DynaSpmId>6.6.3</DynaSpmId>
			<DynaSpmTekst>Hvilken betydning har denne sykdommen for den nedsatte arbeidsevnen?</DynaSpmTekst>
			<Beskrivelse></Beskrivelse>
			<Restriksjon>A</Restriksjon>
			<Obligatorisk>N</Obligatorisk> 
		</DynaSpm>
	</DynaGruppe>
</SM2013DynaSpm>
