=== navikt/Sykmelding_v1.4/konfigurasjon v1.4/xsd/SM2013Ledetekst.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 sp1 (x64) (http://www.altova.com) by XMLSpy 2009 Enterprise Ed., Installed for 30 users (with SMP from 2009-06-19 to 2010-06-20) (NAV Ã˜KONOMITJENESTER) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://nav.no/dokument/ekstern/sykmelding/dynamiskregelsett/SM2013Ledetekst/v1" targetNamespace="http://nav.no/dokument/ekstern/sykmelding/dynamiskregelsett/SM2013Ledetekst/v1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="SM2013Ledetekst">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RegelSettVersjon" type="xs:string">
					<xs:annotation>
						<xs:documentation>Versjon av regelsett</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Ledetekst" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Referanse" type="xs:string"/>
							<xs:element name="Tekst" type="xs:string"/>
							<xs:element name="FeltType" type="xs:string"/>
							<xs:element name="Beskrivelse" type="xs:string" minOccurs="0"/>
							<xs:element name="DynaRegler" type="xs:string" minOccurs="0"/>
							<xs:element name="Restriksjon" type="xs:string" minOccurs="0"/>
							<xs:element name="Obligatorisk" type="xs:boolean" minOccurs="0"/>
							<xs:element name="Mapping" type="xs:string" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="Id" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== navikt/Sykmelding_v1.4/konfigurasjon v1.4/SM2013Ledetekst_v1_4.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SM2013Ledetekst xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://nav.no/dokument/ekstern/sykmelding/dynamiskregelsett/SM2013Ledetekst/v1" xsi:schemaLocation="http://nav.no/dokument/ekstern/sykmelding/dynamiskregelsett/SM2013Ledetekst/v1 SM2013Ledetekst.xsd">
	<RegelSettVersjon>3</RegelSettVersjon>
	<Ledetekst Id="Tittel">
		<Referanse>Tittel</Referanse>
		<Tekst>VURDERING AV ARBEIDSMULIGHET / SYKMELDING</Tekst>
		<FeltType>Tekst</FeltType>
		<Beskrivelse>Tittel</Beskrivelse>
	</Ledetekst>
	<Ledetekst Id="Overskrift">
		<Referanse>Tittel</Referanse>
		<Tekst>FOLKETRYGDEN</Tekst>
		<FeltType>Tekst</FeltType>
		<Beskrivelse>Overskrift</Beskrivelse>
	</Ledetekst>
	<Ledetekst Id="A_overskrift">
		<Referanse>A</Referanse>
		<Tekst>NAVs eksemplar</Tekst>
		<FeltType>Tekst</FeltType>
		<Beskrivelse>Overskrift for NAVs eksemplar</Beskrivelse>
	</Ledetekst>
	<Ledetekst Id="B_overskrift">
		<Referanse>B</Referanse>
		<Tekst>Sykmeldtes eksemplar</Tekst>
		<FeltType>Tekst</FeltType>
		<Beskrivelse>Overskrift for sykmeldtes eksemplar</Beskrivelse>
	</Ledetekst>
	<Ledetekst Id="C_overskrift">
		<Referanse>C</Referanse>
		<Tekst>Arbeidsgivers eksemplar</Tekst>
		<FeltType>Tekst</FeltType>
		<Beskrivelse>Overskrift for arbeidsgivers eksemplar</Beskrivelse>
	</Ledetekst>
	<Ledetekst Id="D_overskrift">
		<Referanse>D</Referanse>
		<Tekst>Krav om sykepenger</Tekst>
		<FeltType>Tekst</FeltType>
		<Beskrivelse>Overskrift for krav om sykepenger</Beskrivelse>
	</Ledetekst>
	<Ledetekst Id="A">
		<Referanse>A</Referanse>
		<Tekst>Sykmelderen skal sende dette eksemplaret til NAV skanning utstedelsesedagen</Tekst>
		<FeltType>Tekst</FeltType>
	</Ledetekst>
	<Ledetekst Id="B">
		<Referanse>B</Referanse>
		<Tekst>Pasienten skal selv beholde dette eksemplaret</Tekst>
		<FeltType>Tekst</FeltType>
	</Ledetekst>
	<Ledetekst Id="C">
		<Referanse>C</Referanse>
		<Tekst>Pasienten skal sende dette eksemplaret til arbeidsgiveren utstedelsesdagen</Tekst>
		<FeltType>Tekst</FeltType>
	</Ledetekst>
	<Ledetekst Id="D">
		<Referanse>D</Referanse>
		<Tekst>Pasienten skal sende kravet til den som skal utbetale sykepenger</Tekst>
		<FeltType>Tekst</FeltType>
	</Ledetekst>
	<Ledetekst Id="SyketilfelleStartDato">
		<Referanse>0</Referanse>
		<Tekst>Når startet det legemeldte fraværet?</Tekst>
		<FeltType>Dato</FeltType>
		<Beskrivelse>Første dato for sykefraværet meldt av sykmelder (lege, kiropraktor og manuellterapeut). Unntatt egenmelding.</Beskrivelse>
		<Obligatorisk>true</Obligatorisk>
		<Mapping>SyketilfelleStartDato</Mapping>
	</Ledetekst>
	<Ledetekst Id="PasientOpplysninger">
		<Referanse>1</Referanse>
		<Tekst>Pasientopplysninger</Tekst>
		<FeltType>Ledetekst</FeltType>
	</Ledetekst>
	<Ledetekst Id="PasientNavn">
		<Referanse>1.1</Referanse>
		<Tekst>Navn</Tekst>
		<FeltType>Tekst</FeltType>
	</Ledetekst>
	<Ledetekst Id="PasientEtternavn">
		<Referanse>1.1.1</Referanse>
		<Tekst>Etternavn</Tekst>
		<FeltType>Tekst</FeltType>
		<Obligatorisk>true</Obligatorisk>
		<Mapping>Pasient/Navn/Etternavn</Mapping>
	</Ledetekst>
	<Ledetekst Id="PasientFornavn">
		<Referanse>1.1.2</Referanse>
		<Tekst>Fornavn</Tekst>
		<FeltType>Tekst</FeltType>
		<Obligatorisk>true</Obligatorisk>
		<Mapping>Pasient/Navn/Fornavn</Mapping>
	</Ledetekst>
	<Ledetekst Id="PasientFodselsnummer">
		<Referanse>1.2</Referanse>
		<Tekst>Fødselsnummer</Tekst>
		<FeltType>Tekst</FeltType>
		<Beskrivelse>Alternativt kan D-nummer legges inn.</Beskrivelse>
		<Obligatorisk>true</Obligatorisk>
		<Mapping>Pasient/Fodselsnummer/Id</Mapping>
	</Ledetekst>
<!--	<Ledetekst Id="PasientTelefon">
		<Referanse>1.3</Referanse>
		<Tekst>Telefon</Tekst>
		<FeltType>Tekst</FeltType>
		<Mapping>Pasient/KontaktInfo/TeleAddress</Mapping>
	</Ledetekst>  -->
<!--	<Ledetekst Id="NavnFastlege">
		<Referanse>1.4</Referanse>
		<Tekst>Navn på pasientens fastlege</Tekst>
		<FeltType>Tekst</FeltType>
		<Mapping>Pasient/NavnFastlege</Mapping>
	</Ledetekst>
	<Ledetekst Id="NAVKontor">
		<Referanse>1.5</Referanse>
		<Tekst>NAV-kontor</Tekst>
		<FeltType>Tekst</FeltType>
		<Beskrivelse>NAV-kontoret pasienten tilhører.</Beskrivelse>
		<Mapping>Pasient/NAVkontor</Mapping>
	</Ledetekst>-->
	<Ledetekst Id="Arbeidsgiver">
		<Referanse>2</Referanse>
		<Tekst>Arbeidsgiver</Tekst>
		<FeltType>Ledetekst</FeltType>
	</Ledetekst>
	<Ledetekst Id="HarArbeidsgiver">
		<Referanse>2.1</Referanse>
		<Tekst>Pasienten har:</Tekst>
		<FeltType>Nedtrekksliste, Kodeverk:HarArbeidsgiver</FeltType>
		<Beskrivelse>Ved flere arbeidsgivere må det registreres en sykmelding for hver.</Beskrivelse>
		<Obligatorisk>false</Obligatorisk>
		<Mapping>Arbeidsgiver/HarArbeidsgiver</Mapping>
	</Ledetekst>
	<Ledetekst Id="NavnArbeidsgiver">
		<Referanse>2.2</Referanse>
		<Tekst>Arbeidsgiver for DENNE sykmeldingen</Tekst>
		<FeltType>Tekst</FeltType>
		<Mapping>Arbeidsgiver/NavnArbeidsgiver</Mapping>
	</Ledetekst>
	<Ledetekst Id="Yrkesbetegnelse">
		<Referanse>2.3</Referanse>
		<Tekst>Yrke/stilling for dette arbeidsforholdet</Tekst>
		<FeltType>Tekst</FeltType>
		<Beskrivelse>Type arbeid er viktig for vurdering av aktivitet og arbeidsevne.</Beskrivelse>
		<Mapping>Arbeidsgiver/Yrkesbetegnelse</Mapping>
	</Ledetekst>
	<Ledetekst Id="Stillingsprosent">
		<Referanse>2.4</Referanse>
		<Tekst>Stillingsprosent</Tekst>
		<FeltType>Tekst</FeltType>
		<Beskrivelse>Prosenten som pasienten er ansatt i hos denne arbeidsgiveren.</Beskrivelse>
		<Mapping>Arbeidsgiver/Stillingsprosent</Mapping>
	</Ledetekst>
	<Ledetekst Id="MedisinskVurdering">
		<Referanse>3</Referanse>
		<Tekst>Diagnose</Tekst>
		<FeltType>Ledetekst</FeltType>
	</Ledetekst>
	<Ledetekst Id="HovedDiagnose">
		<Referanse>3.1</Referanse>
		<Tekst>Hoveddiagnose</Tekst>
		<FeltType>Ledetekst</FeltType>
		<Beskrivelse>Hovedårsak til denne sykmeldingen.</Beskrivelse>
	</Ledetekst>
	<Ledetekst Id="HovedDiagnosesystemS">
		<Referanse>3.1.1</Referanse>
		<Tekst>Kodesystem</Tekst>
		<FeltType>Nedtrekksliste</FeltType>
		<Restriksjon>A</Restriksjon>
		<Mapping>MedisinskVurdering/HovedDiagnose/Diagnosekode/S</Mapping>
	</Ledetekst>
	<Ledetekst Id="HovedDiagnosekodeV">
		<Referanse>3.1.2</Referanse>
		<Tekst>Kode</Tekst>
		<FeltType>Tekst/Nedtrekksliste</FeltType>
		<Beskrivelse>Hovedårsak til denne sykmeldingen.</Beskrivelse>
		<Restriksjon>A</Restriksjon>
		<Mapping>MedisinskVurdering/HovedDiagnose/Diagnosekode/V</Mapping>
	</Ledetekst>
	<Ledetekst Id="HovedDiagnoseTekst">
		<Referanse>3.1.3</Referanse>
		<Tekst>Diagnose</Tekst>
		<FeltType>Tekst</FeltType>
		<Beskrivelse>Hovedårsak til denne sykmeldingen.</Beskrivelse>
		<Restriksjon>A</Restriksjon>
		<Mapping>MedisinskVurdering/HovedDiagnose/Diagnosekode/DN</Mapping>
	</Ledetekst>
	<Ledetekst Id="Bidiagnoser">
		<Referanse>3.2</Referanse>
		<Tekst>Bidiagnoser</Tekst>
		<FeltType>Ledetekst</FeltType>
		<Restriksjon>A</Restriksjon>
	</Ledetekst>
	<Ledetekst Id="BiDiagnosesystemS">
		<Referanse>3.2.1</Referanse>
		<Tekst>Kodesystem</Tekst>
		<FeltType>Nedtrekksliste</FeltType>
		<Restriksjon>A</Restriksjon>
		<Mapping>MedisinskVurdering/BiDiagnoser/Diagnosekode/S</Mapping>
	</Ledetekst>
	<Ledetekst Id="BiDiagnosekodeV">
		<Referanse>3.2.2</Referanse>
		<Tekst>Kode</Tekst>
		<FeltType>Tekst/Nedtrekksliste</FeltType>
		<Restriksjon>A</Restriksjon>
		<Mapping>MedisinskVurdering/BiDiagnoser/Diagnosekode/V</Mapping>
	</Ledetekst>
	<Ledetekst Id="BiDiagnoseTekst">
		<Referanse>3.2.3</Referanse>
		<Tekst>Diagnose</Tekst>
		<FeltType>Tekst</FeltType>
		<Restriksjon>A</Restriksjon>
		<Mapping>MedisinskVurdering/BiDiagnoser/Diagnosekode/DN</Mapping>
	</Ledetekst>
	<Ledetekst Id="AnnenFraversArsak">
		<Referanse>3.3</Referanse>
		<Tekst>Annen lovfestet fraværsgrunn § 8-4, 2. ledd - oppgis hvis relevant</Tekst>
		<FeltType>Ledetekst</FeltType>
		<Restriksjon>A</Restriksjon>
		<Mapping>MedisinskVurdering/AnnenFraversArsak</Mapping>
	</Ledetekst>
	<Ledetekst Id="AnnenFraverArsakskode">
		<Referanse>3.3.1</Referanse>
		<Tekst>Foreligger det annen fraværsgrunn, velg én årsak</Tekst>
		<FeltType>Nedtrekksliste, Kodeverk:AnnenFraversarsak</FeltType>
		<Beskrivelse>Annen fraværsgrunn enn egen sykdom.</Beskrivelse>
		<Restriksjon>A</Restriksjon>
		<Mapping>MedisinskVurdering/AnnenFraversArsak/Arsakskode</Mapping>
	</Ledetekst>
	<Ledetekst Id="AnnenFraverArsakBeskriv">
		<Referanse>3.3.2</Referanse>
		<Tekst>Annen lovfestet fraværsgrunn, beskriv (valgfritt):</Tekst>
		<FeltType>Tekst</FeltType>
		<Beskrivelse>Begrunn annet  lovbestemt fravær.</Beskrivelse>
		<Restriksjon>A</Restriksjon>
		<Mapping>MedisinskVurdering/AnnenFraversArsak/Beskriv</Mapping>
	</Ledetekst>
	<Ledetekst Id="Svangerskap">
		<Referanse>3.4</Referanse>
		<Tekst>Er sykdommen svangerskapsrelatert?</Tekst>
		<FeltType>Sjekkboks</FeltType>
		<Beskrivelse>Gjelder bare dersom sykdommen er forårsaket av svangerskapet.</Beskrivelse>
		<Restriksjon>A</Restriksjon>
		<Mapping>MedisinskVurdering/Svangerskap</Mapping>
	</Ledetekst>
	<Ledetekst Id="Yrkesskade">
		<Referanse>3.5</Referanse>
		<Tekst>Kan sykmeldingen skyldes en yrkesskade/yrkessykdom?</Tekst>
		<FeltType>Sjekkboks</FeltType>
		<Beskrivelse>Gjelder ikke som melding om yrkesskade/yrkessykdom.</Beskrivelse>
		<Restriksjon>A</Restriksjon>
		<Mapping>MedisinskVurdering/Yrkesskade</Mapping>
	</Ledetekst>
	<Ledetekst Id="YrkesskadeDato">
		<Referanse>3.6</Referanse>
		<Tekst>Eventuell skadedato</Tekst>
		<FeltType>Dato</FeltType>
		<Restriksjon>A</Restriksjon>
		<Mapping>MedisinskVurdering/YrkesskadeDato</Mapping>
	</Ledetekst>
	<Ledetekst Id="SkjermesForPasient">
		<Referanse>3.7</Referanse>
		<Tekst>Det er påtrengende nødvendig å skjerme pasienten for medisinske opplysninger, jf. pasient- og brukerrettighetsloven §§ 3-2 og 5-1</Tekst>
