=== navikt/Sykmelding_v1.4/konfigurasjon v1.4/xsd/SM2013DynaRegel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 sp1 (x64) (http://www.altova.com) by XMLSpy 2009 Enterprise Ed., Installed for 30 users (with SMP from 2009-06-19 to 2010-06-20) (NAV ØKONOMITJENESTER) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://nav.no/dokument/ekstern/sykmelding/dynamiskregelsett/SM2013DynaRegel/v1" targetNamespace="http://nav.no/dokument/ekstern/sykmelding/dynamiskregelsett/SM2013DynaRegel/v1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="SM2013DynaRegel">
		<xs:annotation>
			<xs:documentation>Inneholder definisjon av regler</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RegelSettVersjon" type="xs:string">
					<xs:annotation>
						<xs:documentation>Versjon av regelsett</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="DynaRegel" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Definisjon av en dynamisk regel.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Parameter" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>En regel kan ha en eller flere parametersett. Ved flere parametersett skal dette tolkes som "ELLER"</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DiagGruppe_ICPC2" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>En kommaseparert liste med  ICPC-2 diagnosekoder, eller et regulært utrykk </xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="DiagGruppe_ICD10" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>En kommaseparert liste med  ICD-10 diagnosekoder, eller et regulært utrykk </xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="Tidsgruppe" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>En kommaseparert liste med tidspunkt.  Et tidspunkt er oppgitt i antall dager fra start  legemeldt fravær.
"lt" kan benyttes for mindre enn og "gt" benyttes for større enn. </xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="Kjonn" type="xs:string" minOccurs="0"/>
										<xs:element name="AldersGruppe" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>En kommaseparert liste med tidspunkt.  Et tidspunkt er oppgitt i antall år.
"lt" kan benyttes for mindre enn og "gt" benyttes for større enn. Interval lkan oppgis som a-b som betyr at alder er større eller lik a og mindre eller lik b</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Beskrivelse" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Beskrivelse av regel. Kun for  dokumentasjon</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="navn" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Obligatorisk navn på regel. Refereres fra dynamiske spørsmål og ledetekster </xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== navikt/Sykmelding_v1.4/konfigurasjon v1.4/SM2013DynaRegel_v1_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 rel. 3 sp1 (x64) (http://www.altova.com)-->
<SM2013DynaRegel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nav.no/dokument/ekstern/sykmelding/dynamiskregelsett/SM2013DynaRegel/v1 SM2013DynaRegel.xsd" xmlns="http://nav.no/dokument/ekstern/sykmelding/dynamiskregelsett/SM2013DynaRegel/v1"  >
	<RegelSettVersjon>3</RegelSettVersjon>
	<DynaRegel navn="Forenklet">
		<Parameter>
			<DiagGruppe_ICPC2>D70 ,D73 ,F70 ,F72 ,F73 ,H71 ,R72 ,R74 ,R75 ,R76 ,R77 ,R78 ,R80 ,R81 ,U71</DiagGruppe_ICPC2>
			<DiagGruppe_ICD10>A01[0-4]|A02[01289]|A03[012389]|A04[0-9]|A05[0123489]|A06[0-9]|A07[012389]|A08[0-5]|A09|A481|A740|B005|B085|B30[012389]|B580|H00[01]|H01[0189]|H03[018]|H04[34]|H05[01]|H10[0234589]|H13[01238]|H16[123489]|H20[01289]|H21[01234589]|H22[018]|H30[01289]|H32[08]|H579|H66[049]|H67[018]|H7[03]0|J01[0123489]?|J02[089]?|J03[089]?|J04[012]|J050|J06[089]|J09|J1[34]|J10[018]|J11[018]|J12[01289]|J15[0-9]|J16[08]|J17[01238]|J18[01289]|J20[0-9]|J22|J32[0123489]|J36|J40|N30[0123489]|N390|U049</DiagGruppe_ICD10>
			<Tidsgruppe>lt17</Tidsgruppe>
			<Kjonn/>
			<AldersGruppe/>
		</Parameter>
		<Beskrivelse>Sykmeldinger under 16 dager med visse diagnoser</Beskrivelse>
	</DynaRegel>

	<DynaRegel navn="UtdypendeOpplysninger1">
		<Parameter>
			<DiagGruppe_ICPC2></DiagGruppe_ICPC2>
			<DiagGruppe_ICD10></DiagGruppe_ICD10>
			<Tidsgruppe>49</Tidsgruppe>
			<Kjonn/>
			<AldersGruppe/>
		</Parameter>
		<Beskrivelse>Utdypende opplysninger for sykmeldinger som  passerer 7 uker</Beskrivelse>
	</DynaRegel>	
	<DynaRegel navn="UtdypendeOpplysninger2">
		<Parameter>
			<DiagGruppe_ICPC2></DiagGruppe_ICPC2>
			<DiagGruppe_ICD10></DiagGruppe_ICD10>
			<Tidsgruppe>119</Tidsgruppe>
			<Kjonn/>
			<AldersGruppe/>
		</Parameter>
		<Beskrivelse>Utdypende opplysninger for sykmeldinger som  passerer 17 uker</Beskrivelse>
	</DynaRegel>

	<DynaRegel navn="UtdypendeOpplysninger3">
		<Parameter>
			<DiagGruppe_ICPC2></DiagGruppe_ICPC2>
			<DiagGruppe_ICD10></DiagGruppe_ICD10>
			<Tidsgruppe>273</Tidsgruppe>
			<Kjonn/>
			<AldersGruppe/>
		</Parameter>
		<Beskrivelse>Utdypende opplysninger for sykmeldinger som  passerer  39 uker</Beskrivelse>
	</DynaRegel>

	<DynaRegel navn="UtdypendeOpplysninger">
		<Parameter>
			<DiagGruppe_ICPC2></DiagGruppe_ICPC2>
			<DiagGruppe_ICD10></DiagGruppe_ICD10>
			<Tidsgruppe>49,119,273</Tidsgruppe>
			<Kjonn/>
			<AldersGruppe/>
		</Parameter>
		<Beskrivelse>Utdypende opplysninger for sykmeldinger som  passerer 7, 17 og 39 uker</Beskrivelse>
	</DynaRegel>	

	<DynaRegel navn="Symptomdiagnose">
		<Parameter>
			<DiagGruppe_ICPC2>[ABDFHKLNPRSTUWXYZ][0-2][1-9]</DiagGruppe_ICPC2>
			<DiagGruppe_ICD10></DiagGruppe_ICD10>
			<Tidsgruppe>84,273</Tidsgruppe>
			<Kjonn/>
			<AldersGruppe/>
		</Parameter>
		<Parameter>
			<DiagGruppe_ICPC2>P02,P29,A04</DiagGruppe_ICPC2>
			<DiagGruppe_ICD10></DiagGruppe_ICD10>
			<Tidsgruppe>28,196</Tidsgruppe>
			<Kjonn/>
			<AldersGruppe/>
		</Parameter>
		<Beskrivelse>Gjelder alle symptomdiagnoser ved uke 12 og 39, og i tillegg for utvalgte diagnoser i uke 4 og 28.</Beskrivelse>
	</DynaRegel>
	<DynaRegel navn="AvventendeSykmelding">
		<Parameter>
			<DiagGruppe_ICPC2></DiagGruppe_ICPC2>
			<DiagGruppe_ICD10></DiagGruppe_ICD10>
			<Tidsgruppe>lt17</Tidsgruppe>
			<Kjonn/>
			<AldersGruppe/>
		</Parameter>
		<Beskrivelse>Hvis sykefrav√¶rets varighet mindre eller lik 16 dager</Beskrivelse>
	</DynaRegel>
</SM2013DynaRegel>
